version: '3.7'
services:
  poll-service:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongoserver
    links:
      - mongoserver
  mongoserver:
    image: mongo:latest
    ports:
      - 27017:27017